version: 0.0
os: linux

files:
  - source: ./card-service.jar
    destination: /opt/solidnetwork/bank/services

hooks:
  BeforeInstall:
    - location: ./before-install.sh
      timeout: 20
  ApplicationStart:
    - location: ./application-start.sh
      timeout: 40
  ValidateService:
    - location: ./validate-service.sh
      timeout: 40
