version: 0.0
os: linux

files:
  - source: *.jar
    destination: /opt/solidnetwork/bank/services
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: server_stop.sh
      timeout: 20
      runas: ec2-user
  BeforeInstall:
    - location: server_clear.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: add_log_cloudwatch.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: server_start.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: server_validate.sh
      timeout: 40
      runas: ec2-user
